# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GnText < Formula
  desc "Terminal-based GeekNews reader for Korean tech news"
  homepage "https://github.com/sappho192/gn-text"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sappho192/gn-text/releases/download/v0.1.2/gn-text_0.1.2_darwin_amd64.tar.gz"
      sha256 "f180892ba419c948d2f61cc74902e816332dc9574e7232fd7f99804a95c15993"

      def install
        bin.install "gn-text"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sappho192/gn-text/releases/download/v0.1.2/gn-text_0.1.2_darwin_arm64.tar.gz"
      sha256 "9aea8e48ddb51304d99052dbd12ea13eb8d2e1d299072cd470e02fbfc244bbdf"

      def install
        bin.install "gn-text"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sappho192/gn-text/releases/download/v0.1.2/gn-text_0.1.2_linux_amd64.tar.gz"
      sha256 "615faa5c1bbf94c2098230c41368caed6a61861a438382c3dc13a7f6c8253e64"
      def install
        bin.install "gn-text"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sappho192/gn-text/releases/download/v0.1.2/gn-text_0.1.2_linux_arm64.tar.gz"
      sha256 "d12b5ad71a9d723c0fb166f21ca59ed02ff4d8af119e8a5bb38fff1108d2efc3"
      def install
        bin.install "gn-text"
      end
    end
  end
end
